### ISSUE TITLE
Trying to run code/ visualizations on my own trajectron

### ISSUE THREAD

**Issue by keanepotato** [simon-schaefer/mantrap#12]
Dear Simon, 

Keane here. I am thoroughly interested in your research and this project that you have completed. Currently, I am looking to run some of your sample examples (under mantrap/examples) with my own trained trajectron. However, I understand that the trajectron that you use is configured to run a little bit differently, compared to the default trajectron++(https://github.com/StanfordASL/Trajectron-plus-plus). Would you mind letting me have a look at the trajectron model that you are using for mantrap? (I realise that the GenTrajectron folder under mantrap/ third party is not working unfortunately). 

Thank you!
Keane

**Comment by simon-schaefer** [comment]
Hi Keane, 

thank you for the interest in the project and sorry for the late response. 

I did the project during a research internship and therefore I now don't have access to the code base of GenTrajectron anymore, since it is a private repository. Also, I am using a way older model than the open-source version of Trajectron++, that does not support multiple classes, no map encoding, etc., just has a similar network architecture, since the Trajectron++ was not published when I was working on my project.

However, the code should work with the published version of Trajectron++, too. The idea of integrating network gradients into the trajectory planning can be applied to any model, that models the dynamics between the robot and the interacting agent. It just might be slower due to increased model complexity.

I hope I could help you, and sorry for the (partly) negative response!

Best regards, 
Simon
